### ISSUE TITLE
Issue in converting the Map to JSON on the output

### ISSUE THREAD

**Issue by kadimulam** [smartrics/RestFixture#191] opened 2016-05-27 20:39 UTC
We noticed that when the response body contains a Map (example below), the RestFixture is failing to convert it into JSON. The same response body is getting converted when we give the request via Advanced Rest Client.

        Map<Integer, Employee> employeeMap= new HashMap<Integer, Employee>();
        Employee employee = new Employee();
        employee.setSal(1.23);
        employee.setName("Test");
        map.put(new Integer(1), employee);

The JSON response is as below when using FitNesse (assume employeeMap is part of a outer object)
{

  "employeeMap" : { 
    "1" : "**org.mozilla.javascript.UniqueTag@9225652: NOT_FOUND**"
  }

}

Please advice.

**Comment by smartrics** [comment] 2016-05-27 21:23
I don't understand how this can be possible. A java map, if correctly converted to json, is just a plain json object. Anyway - I can't reproduce the issue. It would help to see what is the json produced by the server.

![issue191](https://cloud.githubusercontent.com/assets/140858/15621564/a9c3fc1c-2459-11e6-9d4e-f81e12ddda22.png)

**Comment by kadimulam** [comment] 2016-05-28 02:24
The JSON that i posted previously is the response from the server. Also i see following differences in your request:

1) Your request is GET, could you please try with POST?
2) The object within the Map in your case is containing String, could you please try with a Double field. 

**Note:** Forgot to mention in my previous post, when the same Employee object is placed within a List (example ArrayList), we are not getting this issue. Its only issue with HashMap.

At the moment i cannot provide the response, but i am working with the below simple Controller.
@Controller
@RequestMapping("/employee")
public class EmployeeController {
    
    @RequestMapping(value = "/employees", method=RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)   
    public ResponseEntity<Map> createEmployee(final HttpServletRequest request, final @RequestBody Employee employee){
        Map<Integer, Employee> map = new HashMap<Integer, Employee>();
        employee.setSal(1.23);
        employee.setName("Test");
        map.put(new Integer(1), employee);        
        return new ResponseEntity<Map>(map, HttpStatus.OK);
    }
}

**Comment by smartrics** [comment] 2016-05-28 08:07
Hi, from what you say it's now clear that the issue is in your server side
and not on RestFixture
By the time the response get to the RestFixture it's already a byte stream.
You need to check how your map gets serialised in json before being sent.

**Comment by kadimulam** [comment] 2016-05-28 10:46
Ok, if it is the server issue, how is the Chrome Advanced Rest Client is able to parse it to JSON? I  can suspect the server/Spring Controller if the object was not parsed at both FitNesse & Advanced RestClient. In Advanced Rest Client it works just fine.

**Comment by smartrics** [comment] 2016-05-28 12:39
It may depend on the request you send. For example the content type the
accept header etc.
Please use wireshark or tcpdump to capture both request and response with
both fitnesse ans chrome then compare

**Comment by kadimulam** [comment] 2016-05-31 14:22
Looks like it is an issue with **copyJsonbodyToFile** from **JSONRestFixture**. Please find attached screenshot of FitNesse test, which shows the correct response from the server, however **copyJsonbodyToFile** is writing an incorrect JSON to output file.

To demonstrate this i have created a simple Spring-Boot application, please find the same as attachment which you can use for troubleshooting.

Also, could you please assign this issue to **JSONRestFixture** team once you confirm from your side?

![chrome-output](https://cloud.githubusercontent.com/assets/18126158/15677653/3667a062-2719-11e6-95e2-b7169a0fe989.jpg)
![issue-map](https://cloud.githubusercontent.com/assets/18126158/15677654/366a21ca-2719-11e6-9b27-8f542904ad95.jpg)
[employee-service-example.zip](https://github.com/smartrics/RestFixture/files/291307/employee-service-example.zip)
[JsonRestFixture-GET-Test.txt](https://github.com/smartrics/RestFixture/files/291306/JsonRestFixture-GET-Test.txt)
[actualOutput.txt](https://github.com/smartrics/RestFixture/files/291312/actualOutput.txt)

**Comment by smartrics** [comment] 2016-05-31 16:36
Hi - if you mean this https://github.com/dnygaard/JsonRestFixture you need to take it up with the author (@dnygaard) yourself. This extension is something I was not even aware of.

As this is not an issue related to RestFixture i will close this issue.

**Closed by smartrics** 2016-05-31 16:36 UTC
